### ISSUE TITLE
App quits on windows close / Destroying nonempty message queue

### ISSUE THREAD

**Issue by reggi** [atom/atom-shell#1060]
I have the following code below that opens a about window, for some reason when I close the window the whole app quits with this error. 

```
[5896:0127/173149:WARNING:message_in_transit_queue.cc(18)] Destroying nonempty message queue
```

I found the same error here https://github.com/atom/settings-view/issues/341 @kevinsawicki mentions something about returning false int the commit. 

```
  menu.append(new MenuItem({
    label: 'About',
    type: 'normal',
    click: function() {
      win.show();
      return false
    }
  }));
  tray.setContextMenu(menu);
  var win = new BrowserWindow({ width: 300, height: 150, show: false });
  win.on('closed', function() {
    win = null;
    return false
  });
  win.loadUrl('file://' + __dirname + '/index.html');
```

**Comment by zcbenz** [comment]
This is a problem introduced by Chrome 39 and has already been [fixed in Chrome 40](https://github.com/atom/atom-shell/pull/1002).

**Comment by reggi** [comment]
@zcbenz How do I fix it? Not have a window? When will we have chrome 40 in atom shell? Sorry for the Q's, just really excited to launch my project wanted a simple about / version popup.

**Comment by zcbenz** [comment]
You can write a wrap script that redirects stderr to /dev/null, Chrome always prints some logs into the console even after Chrome 40. Example can be find in `atom.sh`:
https://github.com/atom/atom/blob/master/atom.sh#L91

**Comment by reggi** [comment]
@zcbenz this still doesn't work on v0.21.0 :cry: :car: :monkey_face:
