### ISSUE TITLE
bootstrap.py fails with ssl errors on python 2.7.9

### ISSUE THREAD

**Issue by cldwalker** [atom/atom-shell#998]
Python 2.7.9 introduces some non-trivial ssl changes which seems to cause bootstrap.py to fail. On windows 7 32 bit, I see the following:

```sh
$ /cygdrive/c/Python27/python.exe script/bootstrap.py
Traceback (most recent call last):
  File "script\update-external-binaries.py", line 66, in <module>
    sys.exit(main())
  File "script\update-external-binaries.py", line 31, in main
    download_and_unzip('directxsdk')
  File "script\update-external-binaries.py", line 50, in download_and_unzip
    zip_path = download_framework(framework)
  File "script\update-external-binaries.py", line 61, in download_framework
    download('Download ' + framework, url, path)
  File "C:\cygwin\home\IEUser\code\LightTable\shell\atom-shell\atom-shell\script\lib\util.py", line 48, in download
    web_file = urllib2.urlopen(url)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Traceback (most recent call last):
  File "C:\cygwin\home\IEUser\code\LightTable\shell\atom-shell\atom-shell\script\update.py", line 50, in <module>
    sys.exit(main())
  File "C:\cygwin\home\IEUser\code\LightTable\shell\atom-shell\atom-shell\script\update.py", line 16, in main
    update_external_binaries()
  File "C:\cygwin\home\IEUser\code\LightTable\shell\atom-shell\atom-shell\script\update.py", line 22, in update_external_binaries
    subprocess.check_call([sys.executable, uf])
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'script\\update-external-binaries.py']' returned non-zero exit status 1

Traceback (most recent call last):
  File "script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 34, in main
    update_atom_shell()
  File "script/bootstrap.py", line 123, in update_atom_shell
    execute_stdout([sys.executable, update])
  File "C:\cygwin\home\IEUser\code\LightTable\shell\atom-shell\atom-shell\script\lib\util.py", line 150, in execute_stdout
    execute(argv)
  File "C:\cygwin\home\IEUser\code\LightTable\shell\atom-shell\atom-shell\script\lib\util.py", line 138, in execute
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\cygwin\\home\\IEUser\\code\\LightTable\\shell\\atom-shell\\atom-shell\\script\\update.py']' returned non-zero exit status 1
```
For a possible solution and more background on the python change, [this issue](https://github.com/HenriWahl/Nagstamon/issues/126) may help. Whether this is fixed is up to you. But if it isn't we should put a warning in the build doc to avoid this version. I'll comment on this issue when I've downgraded python on this box.

**Comment by cldwalker** [comment]
Confirmed that python 2.7.8 doesn't have this issue in this environment

**Comment by paulcbetts** [comment]
This is fixed in recent releases - the URL is now an `http` URL instead

**Comment by cldwalker** [comment]
@paulcbetts I see an https url [here](https://github.com/atom/atom-shell/blob/c8ed581e5c141b365b0a1e009ba908f13cf502ce/script/update-external-binaries.py#L12). I encountered this with 0.20.4. If you've verified this is an issue on master with latest python, feel free to close.

**Comment by paulcbetts** [comment]
@cldwalker Oops, didn't look closely, that's another place that should be HTTP (or rather, new Python should ship an updated root cert list :-/)

**Comment by Trixt0r** [comment]
I am still getting this error on Windows 8.1 32-bit and Python 2.7.9.
Here is the log:
```
$ python script/bootstrap.py
Traceback (most recent call last):
  File "script\update-external-binaries.py", line 66, in <module>
    sys.exit(main())
  File "script\update-external-binaries.py", line 31, in main
    download_and_unzip('directxsdk')
  File "script\update-external-binaries.py", line 50, in download_and_unzip
    zip_path = download_framework(framework)
  File "script\update-external-binaries.py", line 61, in download_framework
    download('Download ' + framework, url, path)
  File "C:\Users\IEUser\Desktop\atom-shell\script\lib\util.py", line 48, in download
    web_file = urllib2.urlopen(url)
  File "c:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "c:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "c:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\atom-shell\script\update.py", line 50, in <module>
    sys.exit(main())
  File "C:\Users\IEUser\Desktop\atom-shell\script\update.py", line 16, in main
    update_external_binaries()
  File "C:\Users\IEUser\Desktop\atom-shell\script\update.py", line 22, in update_external_binaries
    subprocess.check_call([sys.executable, uf])
  File "c:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\Python27\\python.exe', 'script\\update-external-binaries.py']' returned non-zero exit status 1

Traceback (most recent call last):
  File "script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 34, in main
    update_atom_shell()
  File "script/bootstrap.py", line 123, in update_atom_shell
    execute_stdout([sys.executable, update])
  File "C:\Users\IEUser\Desktop\atom-shell\script\lib\util.py", line 150, in execute_stdout
    execute(argv)
  File "C:\Users\IEUser\Desktop\atom-shell\script\lib\util.py", line 138, in execute
    raise e
subprocess.CalledProcessError: Command '['c:\\Python27\\python.exe', 'C:\\Users\\IEUser\\Desktop\\atom-shell\\script\\update.py']' returned non-zero exit status 1
```
